### ISSUE TITLE
please resolve the downloading issue ASAP

### ISSUE THREAD

**Issue by neerav555** [biezom/hotstarsportslivestreamer#22]
![voot](https://cloud.githubusercontent.com/assets/24771289/21475993/ff235602-cb58-11e6-8933-6a1b75ac8b42.jpg)

**Comment by neerav555** [comment]
please resolve the downloading issue ASAP

**Comment by Hon3yHd** [comment]
the problem is ad on voot.com b4  there was no ad on video start & after every 6 min there is ad on mobile & website PC... so i know the problem but not the solution but it pretty easy to solve just need modification on .bat file .... but don;t know what uff .......

**Comment by neerav555** [comment]
so please give me a solution if u dnt mind

**Comment by Hon3yHd** [comment]
**here is fix file just replace it on folder {hotstarsportslivestreamer-Master} http://uptobox.com/5xyyrnu9xe6w**

**Comment by neerav555** [comment]
thanks....!!! Hon3yHd

**Comment by paresh996** [comment]
Open voot.php & vootffmpeg.php in notepad.
Change the `$link = 'http://video.voot.com/...` to `$link = 'http://vootvideo.akamaized.net/...` .
Save the file.
Start downloading!

**Comment by Mki-vrm** [comment]
Thanks :+1: .. Paresh996

**Comment by neerav555** [comment]
![image](https://cloud.githubusercontent.com/assets/24771289/24321415/259fb37a-1172-11e7-9a82-47a976023078.png)


please resolve this issue ASAP

**Comment by neerav555** [comment]
![image](https://cloud.githubusercontent.com/assets/24771289/24321491/0ee387b8-1174-11e7-86a2-9b6634298d83.png)

what happening please give me a solution or plz upload a changes file

**Comment by paresh996** [comment]
This is happening because the script fails to get the correct `$flavorId[1]` for some videos and hence the wrong `$link` is used to fetch the m3u8 file. Some developer might know why it happens.

One fix is that you could yourself tell the script where to get the m3u8 file from by providing the `$link`.

I use Mozilla Firefox and here's what you can do : 

1. Download the 'YouTube Downloader - 4K Downloader' add-on in Mozilla Firefox.
![1](https://cloud.githubusercontent.com/assets/25554667/24326567/d4b34a8e-11d6-11e7-9028-d962c1d06855.JPG)

2. Go to the web page of the video you want to download. For example, in @neerav555 's case, it's https://www.voot.com/shows/mtv-unplugged-s06/6/471487/an-unforgettable-musical-night-/479387 .

3. As soon as the web page is loaded and the video starts to play, you'll see the blue button for downloading it beside the web address.
![2](https://cloud.githubusercontent.com/assets/25554667/24326603/db5fd716-11d7-11e7-8bc0-80b159a56705.jpg)

Click on that link shown by the red arrow in the above image. It will ask you where you want to download the video, the location doesn't matter, just click 'Save'.

4. Now close that tab!

5. Go to Firefox downloads and you'll see many fragments which have failed to download. Right-click on any one of them and click 'Copy Download Link'.
![3](https://cloud.githubusercontent.com/assets/25554667/24326678/85a85238-11d9-11e7-8203-3c7859cba1fa.jpg)


6. Now go to the hotstarsportslivestreamer-master folder and make a backup of vootffmpeg.php and voot.php. Now open vootffmpeg.php if you use vootffmpeg.bat or voot.php if you use vootlivestreamer.bat in Notepad or Notepad++ and paste the link you copied into the `$link` string variable. **Replace the 'seg-*-v*-a*.ts' as 'index.m3u8'** : 
![4](https://cloud.githubusercontent.com/assets/25554667/24326644/d2e9f142-11d8-11e7-9bea-8de11111ca04.JPG)

7. Open vootffmpeg.bat or vootlivestreamer.bat whichever you use and paste the link of the video as usual. Type a bitrate and press enter. The video will get downloaded.
![5](https://cloud.githubusercontent.com/assets/25554667/24326665/596c5a48-11d9-11e7-8ea3-46701ce5a342.jpg)

💯 % works.

**8. Now, delete this file that you edited and put the backup back in it's place or just undo the `$link ` change and then the streamer will work for other videos.**

**Comment by neerav555** [comment]
i want to change the string in both file vootffmpeg or voot please tell me where i want to change the string
& i also send you a string if you dont mind then you modifying the file then send me modified file?
https://vootvideo.akamaized.net/enc/fhls/p/1982551/sp/198255100/serveFlavor/entryId/0_u1n12ps5/v/32/pv/1/flavorId/0_4ztauknr/name/a.mp4/index.m3u8

**Comment by neerav555** [comment]
@paresh996 i want to change the string in both file vootffmpeg or voot please tell me where i want to change the string
& i also send you a string if you dont mind then you modifying the file then send me modified file?
https://vootvideo.akamaized.net/enc/fhls/p/1982551/sp/198255100/serveFlavor/entryId/0_u1n12ps5/v/32/pv/1/flavorId/0_4ztauknr/name/a.mp4/index.m3u8

**Comment by neerav555** [comment]
@paresh996 
![image](https://cloud.githubusercontent.com/assets/24771289/24328835/fa5414b8-1211-11e7-9a6f-42be0e6a2bd4.png)

i will tried many times but some error occurred so please can you send me modified files if you dont mind

**Comment by neerav555** [comment]
@paresh996 Hey buddy dont working out on it its done now its working thanks a lot

**Comment by neerav555** [comment]
any one suggest downloader for sony liv accept 9xbuddy.com its doesnt have hd video quality so i want to download hd videos from sony liv if any know then suggest me please!!!

**Comment by neerav555** [comment]
@paresh996 
![image](https://cloud.githubusercontent.com/assets/24771289/24330765/5c6ea844-1243-11e7-8396-49ffe5993482.png)


i replace a link which you  show me in further step its working but also some problem it has when i entered a bitrate 2628 its not downloading in 2628 its download in a 640 x 360 so please give me a solution

**Comment by neerav555** [comment]
![image](https://cloud.githubusercontent.com/assets/24771289/24330765/5c6ea844-1243-11e7-8396-49ffe5993482.png)


i replace a link which you  show me in further step its working but also some problem it has when i entered a bitrate 2628 its not downloading in 2628 its download in a 640 x 360 so please give me a solution

any one suggest downloader for sony liv accept 9xbuddy.com its doesnt have hd video quality so i want to download hd videos from sony liv if any know then suggest me please!!!

**Comment by paresh996** [comment]
Don't know about it... It always detects only 640 x 360!
![untitled](https://cloud.githubusercontent.com/assets/25554667/24370834/736904e6-1346-11e7-9eb0-00d31010b5e0.jpg)

**Comment by neerav555** [comment]
@paresh996  thanks buddy

**Comment by neerav555** [comment]
any one suggest downloader for sony liv accept 9xbuddy.com its doesnt have hd video quality so i want to download hd videos from sony liv if any know then suggest me please!!!

**Comment by coolkool86** [comment]
Friends,
I followed the same steps but still no luck and getting the below error.

![voot](https://cloud.githubusercontent.com/assets/26851496/24586507/6def02b2-17c0-11e7-85f8-8ab49f1f102e.jpg)

Need to download the below show. Kindly assist. Much appreciate for your response.
https://www.voot.com/shows/comedy-nights-bachao/1/360658/team-baar-baar-dekho-light-up-the-stage/444294
